-- AlterTable
ALTER TABLE `Event` ADD COLUMN `bulletPoints` JSON NULL,
    ADD COLUMN `standSubtitle` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('PUBLISHED', 'SCHEDULED', 'DRAFT') NOT NULL DEFAULT 'DRAFT',
    ADD COLUMN `type` ENUM('FAIR_EXPO', 'IN_STORE', 'POP_UP', 'ONLINE') NOT NULL DEFAULT 'FAIR_EXPO',
    ADD COLUMN `venueCallout` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `EventImage` ADD COLUMN `role` ENUM('POSTER', 'HERO', 'GALLERY') NOT NULL DEFAULT 'GALLERY';

