export type ExportSection = {
  title: string;
  headers: string[];
  rows: (string | number)[][];
};

export type ExportScopeOption = {
  key: string;
  label: string;
  getSections: () => ExportSection[];
};

function csvField(value: string | number): string {
  const text = String(value);
  return /[,"\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

export function buildCsv(sections: ExportSection[]): string {
  const lines: string[] = [];
  sections.forEach((section, index) => {
    if (index > 0) lines.push("");
    lines.push(`# ${section.title}`);
    lines.push(section.headers.map(csvField).join(","));
    section.rows.forEach((row) => lines.push(row.map(csvField).join(",")));
  });
  return lines.join("\n");
}

function escapePdfText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

type RGB = [number, number, number];

const BRAND_DARK: RGB = [0.33, 0.19, 0.09];
const BRAND_ACCENT: RGB = [0.79, 0.59, 0.23];
const HEADER_ROW_BG: RGB = [0.95, 0.91, 0.84];
const ROW_STRIPE_BG: RGB = [0.98, 0.96, 0.93];
const TEXT_DARK: RGB = [0.15, 0.12, 0.1];
const TEXT_MUTED: RGB = [0.5, 0.46, 0.42];
const WHITE: RGB = [1, 1, 1];
const CREAM: RGB = [0.94, 0.87, 0.76];

const PAGE_WIDTH = 612;
const MARGIN_X = 50;
const TABLE_WIDTH = PAGE_WIDTH - MARGIN_X * 2;
const ROW_HEIGHT = 20;

function rect(x: number, y: number, w: number, h: number, color: RGB): string {
  return `${color.join(" ")} rg\n${x} ${y} ${w} ${h} re\nf\n`;
}

function text(x: number, y: number, font: "F1" | "F2", size: number, color: RGB, value: string): string {
  return `${color.join(" ")} rg\nBT\n/${font} ${size} Tf\n${x} ${y} Td\n(${escapePdfText(value)}) Tj\nET\n`;
}

export function buildSimplePdf(title: string, subtitle: string, sections: ExportSection[]): Blob {
  let stream = "";
  let y = 792;

  const headerHeight = 88;
  y -= headerHeight;
  stream += rect(0, y, PAGE_WIDTH, headerHeight, BRAND_DARK);
  stream += rect(0, y, 6, headerHeight, BRAND_ACCENT);
  stream += text(MARGIN_X, y + headerHeight - 34, "F2", 22, WHITE, title);
  stream += text(MARGIN_X, y + headerHeight - 56, "F1", 11, CREAM, subtitle);

  y -= 34;

  sections.forEach((section) => {
    y -= 8;
    stream += rect(MARGIN_X, y - 2, 3, 16, BRAND_ACCENT);
    stream += text(MARGIN_X + 12, y, "F2", 13, BRAND_DARK, section.title);
    y -= 26;

    const colWidth = TABLE_WIDTH / section.headers.length;

    stream += rect(MARGIN_X, y - 6, TABLE_WIDTH, ROW_HEIGHT, HEADER_ROW_BG);
    section.headers.forEach((header, colIndex) => {
      stream += text(MARGIN_X + colIndex * colWidth + 8, y, "F2", 9, BRAND_DARK, header.toUpperCase());
    });
    y -= ROW_HEIGHT;

    section.rows.forEach((row, rowIndex) => {
      if (rowIndex % 2 === 1) {
        stream += rect(MARGIN_X, y - 6, TABLE_WIDTH, ROW_HEIGHT, ROW_STRIPE_BG);
      }
      row.forEach((cell, colIndex) => {
        stream += text(MARGIN_X + colIndex * colWidth + 8, y, "F1", 9.5, TEXT_DARK, String(cell));
      });
      y -= ROW_HEIGHT;
    });

    y -= 18;
  });

  stream += text(MARGIN_X, 40, "F1", 8, TEXT_MUTED, "Generated by Munay Admin");

  const objects: string[] = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /MediaBox [0 0 612 792] /Contents 4 0 R >>",
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
  ];

  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];
  objects.forEach((obj, index) => {
    offsets.push(pdf.length);
    pdf += `${index + 1} 0 obj\n${obj}\nendobj\n`;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: "application/pdf" });
}

function escapeHtml(value: string | number): string {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function buildExcelWorkbook(sections: ExportSection[]): Blob {
  const tables = sections
    .map((section) => {
      const headerRow = `<tr>${section.headers
        .map((h) => `<th style="background:#f4ece0;font-weight:bold;padding:6px 10px;border:1px solid #e8e6e1;">${escapeHtml(h)}</th>`)
        .join("")}</tr>`;
      const bodyRows = section.rows
        .map(
          (row) =>
            `<tr>${row
              .map((cell) => `<td style="padding:6px 10px;border:1px solid #e8e6e1;">${escapeHtml(cell)}</td>`)
              .join("")}</tr>`,
        )
        .join("");
      return `<p style="font-weight:bold;font-size:14px;margin:16px 0 6px;">${escapeHtml(section.title)}</p><table style="border-collapse:collapse;font-family:sans-serif;font-size:12px;">${headerRow}${bodyRows}</table>`;
    })
    .join("");

  const html = `<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8" /></head><body>${tables}</body></html>`;
  return new Blob([html], { type: "application/vnd.ms-excel" });
}

export function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
